### ISSUE TITLE
USER STORY: Site content

### ISSUE THREAD

**Issue by JPatel87** [JPatel87/locks-of-lush#1]
As a site user I want to view salon contact details, reviews and services so that I feel well informed before making a booking.

## Acceptance criteria: 

* Acceptance criteria 1: Site has salon contact details as a separate page from the home page.
* Acceptance criteria 2: Site has reviews on the home page.
* Acceptance criteria 3: Site has salon service information as a separate page from the home page.

## Tasks:

- [ ] Task 1: Create an index.html page containing reviews and "contact us" and "services" navbar links.
- [ ] Task 2: Create a "contact us" page and link back to index.html page.
- [ ] Task 3: Create a "services" page and link back to index.html page.

**Comment by JPatel87** [comment]
Refine user stories - removing reviews
