### ISSUE TITLE
USER STORY: Site content 

### ISSUE THREAD

**Issue by JPatel87** [JPatel87/locks-of-lush#1]
As a site user I want to view salon services, prices and stylist details so that I feel confident in my decision to make a booking.

## Acceptance criteria: 

* Acceptance criteria 1: Site has a salon services page which includes prices.
* Acceptance criteria 2: Site has a salon stylists page which has stylist price details.

## Tasks:

- [ ] Task 1: Create home page with "services" and “stylists” navbar links
- [ ] Task 2: Create a services html page
- [ ] Task 3: Create a stylists html page
- [ ] Task 4: Create a database for services which can be edited by the admin. Updates occur automatically on the services page
- [ ] Task 5: Create a database for stylists which can be edited by the admin. Updates occur automatically on the stylists page

**Comment by JPatel87** [comment]
Completed task 2 and task 4

**Comment by JPatel87** [comment]
Completed tasks 3 and 5 - basic page content

**Comment by JPatel87** [comment]
Added additional tasks to style home, services and stylist pages using Bootstrap

**Comment by JPatel87** [comment]
Removed tasks 4-6 and added to another user story
