### ISSUE TITLE
USER STORY B4: Edit bookings

### ISSUE THREAD

**Issue by JPatel87** [JPatel87/locks-of-lush#12]
As a site user I want to be able to edit my booking from my account so that I can make changes at a time that is convenient for me. 

## Acceptance criteria: 

* Acceptance criteria 1: Users can change details of an upcoming booking through the click of an "Change" button from their user account profile
* Acceptance criteria 2: Users cannot change details of a past booking
* Acceptance criteria 3: Users can make changes to all fields; date, time, service and stylist

## Tasks:

- [x] Task 1: Create an "Change" button to appear besides upcoming bookings, in the user account profile
- [x] Task 2: Ensure "Change" buttons do not appear besides past bookings.
- [x] Task 3: When an "Edit" button is selected - ensure users are able to make changes to the date, time service and stylist details
