### ISSUE TITLE
USER STORY B5: Cancel bookings

### ISSUE THREAD

**Issue by JPatel87** [JPatel87/locks-of-lush#13]
As a site user I want to be able to cancel my booking from my account so that I can free up my appointment slot for somebody else

## Acceptance criteria: 

* Acceptance criteria 1: Users can cancel details of an upcoming booking through the click of a "Cancel" button from their user account profile
* Acceptance criteria 2: Users cannot delete a past booking
* Acceptance criteria 3: Users are given the option to confirm a deletion before an appointment is deleted

## Tasks:

- [x] Task 1: Create a "Cancel" button to appear besides upcoming bookings, in the user account profile
- [x] Task 2: Ensure "Cancel" buttons do not appear besides past bookings
- [x] Task 3: When a "Cancel" button is selected - a prompt is displayed to the user to confirm the deletion
