### ISSUE TITLE
USER STORY C2: Manage services

### ISSUE THREAD

**Issue by JPatel87** [JPatel87/locks-of-lush#14]
As a site admin I want to be able to create, read, update and delete service details through the site login so that I have control over the information displayed on the site to make sure it is current. 

## Acceptance criteria: 

* Acceptance criteria 1: There is a services database model which includes service name and price details fields
* Acceptance criteria 2: Only the admin has access to add, update, delete services from the database
* Acceptance criteria 3: Changes made to the service name and price are reflected on the site

## Tasks:

- [x] Task 1: Create a services model with service name and price details fields
- [x] Task 2: Restrict access on the site login to allow only the admin to add, update and delete services
- [x] Task 3: Create a forms.py file and create a django services form inside and update views file with form name
- [x] Task 4: Create an add services html page, update views file, update urls file
- [x] Task 5: Create an edit services html page, update views file, update urls file
- [x] Task 6: Create a delete services html page, update views file, update urls file

**Comment by JPatel87** [comment]
Update user story to remove stylist management

**Comment by JPatel87** [comment]
Update to include django service form task
