### ISSUE TITLE
USER STORY C1: Manage user bookings

### ISSUE THREAD

**Issue by JPatel87** [JPatel87/locks-of-lush#15]
As a site admin I want to be able to create, read, update and delete user bookings so that I am aware of the bookings that are being made and can edit/delete them if required. 

## Acceptance criteria: 

* Acceptance criteria 1:  The admin can see all booked appointments from all users
* Acceptance criteria 2:  Non admin users cannot see booked appointments from all users
* Acceptance criteria 3:  The admin account can view, edit or delete user bookings.

## Tasks:

- [x] Task 1:  There is a bookings database containing all bookings which can only be accessed from the admin account
- [x] Task 2:  Non-admin users do not have access to the complete bookings database
- [x] Task 3: Admin can perform the same functionality to that of the user; view, edit or delete bookings.
