### ISSUE TITLE
USER STORY B6: Add reviews

### ISSUE THREAD

**Issue by JPatel87** [JPatel87/locks-of-lush#16]
As a site user I want to be able to add a review after my appointment so that the salon can improve/maintain its services

## Acceptance criteria: 

* Acceptance criteria 1: -	After a appointment has occurred – users will be given the option to add a review, from their user account profile
* Acceptance criteria 2: Users should not be given the option to add a review for upcoming appointments
* Acceptance criteria 2: If a review is made, it will be sent to the admin to approve

## Tasks:

- [ ] Task 1:  Create a "Add review" button following an appointment in the past
- [ ] Task 2:  Create a review model
- [ ] Task 3: All submitted reviews go to the admin to review
