### ISSUE TITLE
USER STORY C4: Manage stylists

### ISSUE THREAD

**Issue by JPatel87** [JPatel87/locks-of-lush#18]
As a site admin I want to be able to create, read, update and delete stylist details through the site login so that I have control over the information displayed on the site to make sure it is current. 

## Acceptance criteria: 

* Acceptance criteria 1: There is a stylist database model which contains first name, last name, telephone number, email address, image and background fields.
* Acceptance criteria 2: Only the admin has access to add, update, delete stylists from the website. 
* Acceptance criteria 3: Changes made to the stylist details through the admin site login are reflected on the site.

## Tasks:

- [x] Task 1: Create a stylist model with first name, last name, telephone number, email address, image and background fields.
- [ ] Task 2: Restrict access on the site login to allow only the admin to add, update and delete stylist details.
- [ ] Task 3: Create a forms.py file and create a django stylist form inside and update views file with form name
- [ ] Task 4: Create an add stylist html page, update views file, update urls file
- [ ] Task 5: Create an edit stylist html page, update views file, update urls file
- [ ] Task 6: Create a delete stylist html page, update views file, update urls file

**Comment by JPatel87** [comment]
Add task to create django stylist form
