### ISSUE TITLE
USER STORY: Make bookings

### ISSUE THREAD

**Issue by JPatel87** [JPatel87/locks-of-lush#2]
As a site user I want to book appointments from the website so that I have more control over my bookings.

## Acceptance criteria: 

* Acceptance criteria 1:  Site has a bookings page which allows users to make a booking by selecting the appropriate service, stylist and date and time of their appointment.

## Tasks:

- [ ] Task 1:  Create a home page with a "bookings" navbar link
- [ ] Task 2:  Create a bookings html page.
- [ ] Task 3: Create a bookings database.
