### ISSUE TITLE
USER STORY: User account

### ISSUE THREAD

**Issue by JPatel87** [JPatel87/locks-of-lush#2]
As a **site user** I want **to create a user account** so that **I can manage my bookings**

## Acceptance criteria: 

* Acceptance criteria 1: A log-in link should appear in the site header.
* Acceptance criteria 2: A log-in modal should appear when the log-in link is selected to allow registered users to sign in with a username and password. There should also be a link in the modal for new users to sign-up. 
* Acceptance criteria 3: The sign-up link opens up a sign-up modal where additional user details are required to create a new user account. 

## Tasks:

- [ ] Task 1: Create a log-in link in header of the site.
- [ ] Task 2: Create a log-in modal with username and password fields as well as a submit button.
- [ ] Task 3: Create a sign-up modal with first name, last name, contact number, email and password fields. In addition to password guideline information.
