### ISSUE TITLE
USER STORY: Cancel an appointment

### ISSUE THREAD

**Issue by JPatel87** [JPatel87/locks-of-lush#4]
As a site user I want to be able to cancel appointments from my user account so that I have more control over my bookings.

## Acceptance criteria: 

* Acceptance criteria 1:  There is a “cancel appointments” button in the user account related to every upcoming appointment. 
* Acceptance criteria 2:  The "cancel appointments" button opens up a cancellation modal which allows users to confirm their cancellation before submitting their request.
* Acceptance criteria 3:  After submitting the cancellation request, the bookings database is updated.

## Tasks:

- [ ] Task 1:  Create a "cancel appointments" button in the user account beside each appointment. 
- [ ] Task 2:  Create a "cancel appointments" modal and link it to the "cancel appointments" button. The cancel modal should summarise the appointment details. A "confirm" button should be present in the modal. 
- [ ] Task 3: Link the cancellation request, once confirmed, to the bookings database and ensure it updates to remove the booking.
