### ISSUE TITLE
USER STORY: Add reviews

### ISSUE THREAD

**Issue by JPatel87** [JPatel87/locks-of-lush#5]
As a site user I want to add reviews about services so that others know what to expect.

## Acceptance criteria: 

* Acceptance criteria 1: Once an appointment has occurred, the user will be sent an inbox message in their user account to add a review.
* Acceptance criteria 2: By clicking on the review link, a review modal will appear with a blank field allowing the user to add a review, then submit it. 
* Acceptance criteria 3: The submitted review will go to the user admin account. 

## Tasks:

- [ ] Task 1: Create an automatic review message to user accounts, following an appointment.
- [ ] Task 2:  Create a review modal with a large empty field and a submit button and link it to the review link in the review message.
- [ ] Task 3: Link review requests from all user accounts to the admin account so all reviews are submitted to the admin account.
