### ISSUE TITLE
USER STORY A1: Attractive site

### ISSUE THREAD

**Issue by JPatel87** [JPatel87/locks-of-lush#6]
As a site user I want to be able to view a site which is attractive yet informative so that I can gain an understanding of the sites purpose and feel inspired to view its related content.

## Acceptance criteria: 

* Acceptance criteria 1: Site has home page with a logo, hero image and catchy slogan
* Acceptance criteria 2: Site has clear navigation links 
* Acceptance criteria 3: Site has clear colour scheme and consistent typography

## Tasks:

- [x] Task 1: Create a home page with a logo, hero image and catchy slogan
- [x] Task 2: Create a header with a navigation menu 
- [x] Task 3: Find a colour scheme consisting of maximum 3 colours appropriate to the website target audience
- [x] Task 4: Find a typography for the body text and for main headings
