### ISSUE TITLE
USER STORY B1: User account

### ISSUE THREAD

**Issue by JPatel87** [JPatel87/locks-of-lush#9]
As a site user I want to be able to create a user account so that I can login to make a booking and logout once I am done.

## Acceptance criteria: 

* Acceptance criteria 1: Users can click on links to sign up/log in when they choose to make a booking
* Acceptance criteria 2: Users are directed to the sign up page when they choose to sign up
* Acceptance criteria 3: Users are directed to the log in page when they choose to log in
* Acceptance criteria 4: Users are directed to the log out page when they choose to log out

## Tasks:

- [x] Task 1: Create navigation links to login or sign up when a user wants to make a booking
- [x] Task 2: Create a sign up page using Allauth
- [x] Task 3: Create a log in page using Allauth
- [x] Task 4: Create a log out page using Allauth
