### ISSUE TITLE
USER STORY: Site appeal

### ISSUE THREAD

**Issue by JPatel87** [JPatel87/locks-of-lush#9]
As a site owner I want the site to look appealing to entice new customers to make a booking. 

## Acceptance criteria: 

* Acceptance criteria 1: Ensure the site navigation is distinctive and has clear links to the salon and service pages.
* Acceptance criteria 2: In the header include the salon name and login link and in the footer have social media links. 
* Acceptance criteria 3: Include photos of haircut designs and the salon in the site.

## Tasks:

- [ ] Task 1: Create a header with the salon name and login link.
- [ ] Task 2: Create a footer with the salon name and social media links.
- [ ] Task 3: Include photos of haircut designs in the home page and service page and the salon photo in the contact us page.
